volumes:
  pg_data_prodaction:
  static_prodaction:
  media_prodaction:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data_prodaction:/var/lib/postgresql/data
  backend:
    image: ilyabackend/foodgram_backend
    env_file: .env
    volumes:
      - static_prodaction:/backend_static
      - media_prodaction:/app/media
    depends_on:
      - db
  frontend:
    image: ilyabackend/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_prodaction:/frontend_static
  gateway:
    image: ilyabackend/foodgram_gateway
    env_file: .env
    volumes:
      - static_prodaction:/staticfiles
      - media_prodaction:/app/media/
    ports:
      - 7000:80
    depends_on:
      - backend
      - frontend
